[package]
name = "f2brad-host"
version = "0.1.0"
edition = "2021"
authors = ["ZHANG Yufeng"]
description = "Host genotyping arm for fast2bRAD-holo"

[[bin]]
name = "f2brad-host"
path = "src/main.rs"

[dependencies]
f2brad-core = { path = "../f2brad-core" }

anyhow = "1.0"
clap = { version = "4.0", features = ["derive"] }
fxhash = "0.2"
indicatif = { version = "0.17", features = ["rayon"] }
rayon = "1.8"
tracing = "0.1"
tracing-subscriber = "0.3"
needletail = "0.5"
